### ISSUE TITLE
Unpacked venv-pack must currently use same path as original

### ISSUE THREAD

**Issue by jenisys** [jcrist/venv-pack#13] opened 2018-09-06 13:22 UTC
PLATFORM: Windows (at least)

Currently, the `VIRTUAL_ENV` environment variable is not corrected in the `activate*` script of the "unpacked venv-pack".
Therefore, you can only use it if unpack it in the same absolute location on the new machine like the original virtual environment.

SIMILAR: `conda-unpack` functionality

**Comment by jcrist** [comment] 2018-09-06 13:43
This is only true for windows (which is currently unsupported). We have tests for this on linux/osx. Closing as duplicate of #6.

**Closed by jcrist** 2018-09-06 13:43 UTC

**Comment by jenisys** [comment] 2018-09-06 22:45
NOTE: Seems to be a problem how the `activate.bat` script is created by `virtualenv` / `venv`.
DOS batchfile have a solution to emulate the dirname/basename functionality that is used in the Bourne shell script `activate`.
